<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Project;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            [
                'title' => 'Deep Blue Feature Wall & Living Room Fireplace',
                'category' => 'Painting & Decorating',
                'categoryKey' => 'painting',
                'location' => 'Liverpool City Centre',
                'tag' => 'Feature Wall',
                'image' => '/images/gallery/sk-home-solutions-deep-blue-feature-wall-with-fireplace.jpeg',
                'description' => 'Rich royal blue accent wall surrounding a contemporary fireplace with clean cut lines and smooth emulsion finish.',
                'status' => 'Active',
            ],
            [
                'title' => 'Contemporary TV Media Feature Wall Design',
                'category' => 'TV Media Walls & Mounting',
                'categoryKey' => 'media-wall',
                'location' => 'Liverpool City Centre',
                'tag' => 'Media Wall',
                'image' => '/images/gallery/sk-home-solutions-contemporary-tv-feature-wall-design.jpeg',
                'description' => 'Custom built-in TV media wall with hidden cable routing, floating console, and modern accent backlighting.',
                'status' => 'Active',
            ],
            [
                'title' => 'Bespoke Wooden Wine Storage & Display Unit',
                'category' => 'Carpentry & Joinery',
                'categoryKey' => 'carpentry',
                'location' => 'Formby, Merseyside',
                'tag' => 'Custom Woodwork',
                'image' => '/images/gallery/sk-home-solutions-bespoke-wooden-wine-storage-unit.jpeg',
                'description' => 'Custom handcrafted timber wine rack and display cabinetry tailored to fit dining room dimensions perfectly.',
                'status' => 'Active',
            ],
            [
                'title' => 'Botanical Floral Feature Wallpaper Installation',
                'category' => 'Wallpapering & Murals',
                'categoryKey' => 'wallpaper',
                'location' => 'Aigburth, Liverpool',
                'tag' => 'Wallpapering',
                'image' => '/images/gallery/sk-home-solutions-botanical-floral-wallpaper-installation.jpeg',
                'description' => 'Precision hung luxury botanical floral wallpaper with seamless pattern alignment and bubble-free finish.',
                'status' => 'Active',
            ],
            [
                'title' => 'Handcrafted Classic Dovetail Joint Woodwork',
                'category' => 'Carpentry & Joinery',
                'categoryKey' => 'carpentry',
                'location' => 'Crosby, Liverpool',
                'tag' => 'Fine Joinery',
                'image' => '/images/gallery/sk-home-solutions-classic-dovetail-joint-woodwork.jpeg',
                'description' => 'Traditional master carpentry showcasing interlocking dovetail joint construction for high-end furniture.',
                'status' => 'Active',
            ],
            [
                'title' => 'Modern Blue Accent Wall Bedroom Transformation',
                'category' => 'Painting & Decorating',
                'categoryKey' => 'painting',
                'location' => 'Aigburth, Liverpool',
                'tag' => 'Interior Decorating',
                'image' => '/images/gallery/sk-home-solutions-modern-blue-accent-wall-bedroom-design.jpeg',
                'description' => 'Serene deep blue feature bedroom wall paired with warm wooden bed frame and precision painted woodwork.',
                'status' => 'Active',
            ],
            [
                'title' => 'Elegant Timber Wall Panelling & Wainscoting',
                'category' => 'Carpentry & Joinery',
                'categoryKey' => 'carpentry',
                'location' => 'Aigburth, Liverpool',
                'tag' => 'Wall Panelling',
                'image' => '/images/gallery/sk-home-solutions-elegant-wood-panelled-living-room-design.jpeg',
                'description' => 'Architectural wood panelling installed across the living room wall for luxury aesthetic and thermal insulation.',
                'status' => 'Active',
            ],
            [
                'title' => 'Designer Feather Mural Wallpaper Application',
                'category' => 'Wallpapering & Murals',
                'categoryKey' => 'wallpaper',
                'location' => 'Crosby, Liverpool',
                'tag' => 'Mural Hanging',
                'image' => '/images/gallery/sk-home-solutions-feather-design-mural-wallpaper.jpeg',
                'description' => 'Statement wall mural installation featuring soft feather motifs, razor trimmed against skirting and ceiling line.',
                'status' => 'Active',
            ],
            [
                'title' => 'Heavy-Duty Timber Garden Pergola Structure',
                'category' => 'Carpentry & Joinery',
                'categoryKey' => 'carpentry',
                'location' => 'Formby, Merseyside',
                'tag' => 'Outdoor Carpentry',
                'image' => '/images/gallery/sk-home-solutions-outdoor-pergola-garden-structure.jpeg',
                'description' => 'Treated structural softwood outdoor pergola handcrafted for a residential garden patio in Formby.',
                'status' => 'Active',
            ],
            [
                'title' => 'Precision Blue Emulsion Wall Coating',
                'category' => 'Painting & Decorating',
                'categoryKey' => 'painting',
                'location' => 'Crosby, Liverpool',
                'tag' => 'Wall Painting',
                'image' => '/images/gallery/sk-home-solutions-fresh-blue-wall-paint-application.jpg',
                'description' => 'Flawless roller application of premium scrubbable matt emulsion with perfect brush cutting around fixtures.',
                'status' => 'Active',
            ],
            [
                'title' => 'Geometric Accent Wall Pattern Painting',
                'category' => 'Painting & Decorating',
                'categoryKey' => 'painting',
                'location' => 'Formby, Merseyside',
                'tag' => 'Decorative Painting',
                'image' => '/images/gallery/sk-home-solutions-geometric-accent-wall-painting-design.jpeg',
                'description' => 'Crisp multi-tone geometric accent wall created using precision low-tack tape for ultra-sharp color separation.',
                'status' => 'Active',
            ],
            [
                'title' => 'Living Room TV Wall Bracket Mount & Setup',
                'category' => 'TV Media Walls & Mounting',
                'categoryKey' => 'media-wall',
                'location' => 'Allerton, Liverpool',
                'tag' => 'TV Mounting',
                'image' => '/images/gallery/sk-home-solutions-professional-tv-wall-mounting-service.jfif',
                'description' => 'Secure stud-wall TV bracket installation with reinforced anchors, clean concealed cabling, and level alignment.',
                'status' => 'Active',
            ],
            [
                'title' => 'Fine Dovetail Solid Timber Drawer Construction',
                'category' => 'Carpentry & Joinery',
                'categoryKey' => 'carpentry',
                'location' => 'Allerton, Liverpool',
                'tag' => 'Fine Joinery',
                'image' => '/images/gallery/sk-home-solutions-fine-dovetail-drawer-joinery.jpeg',
                'description' => 'Precision hand-fitted solid hardwood drawer boxes demonstrating master cabinetmaking techniques.',
                'status' => 'Active',
            ],
            [
                'title' => 'Seamless Pattern Floral Wallpaper Hanging',
                'category' => 'Wallpapering & Murals',
                'categoryKey' => 'wallpaper',
                'location' => 'Allerton, Liverpool',
                'tag' => 'Wallpapering',
                'image' => '/images/gallery/sk-home-solutions-floral-wallpaper-hanging-service.jpeg',
                'description' => 'Expert hanging of intricate repeat-pattern wallpaper with invisible vertical seams and flawless corner tucks.',
                'status' => 'Active',
            ],
            [
                'title' => 'Navy Blue Living Room Interior Decor',
                'category' => 'Painting & Decorating',
                'categoryKey' => 'painting',
                'location' => 'Allerton, Liverpool',
                'tag' => 'Full Room Paint',
                'image' => '/images/gallery/sk-home-solutions-navy-blue-living-room-interior-inspiration.jpeg',
                'description' => 'Sophisticated dark navy blue interior room finish with high-contrast bright white ceiling and woodwork.',
                'status' => 'Active',
            ],
            [
                'title' => 'Modern Floating Timber Shelving & Dividers',
                'category' => 'Carpentry & Joinery',
                'categoryKey' => 'carpentry',
                'location' => 'Woolton, Liverpool',
                'tag' => 'Bespoke Shelving',
                'image' => '/images/gallery/sk-home-solutions-modern-wood-shelf-with-coloured-dividers.jpeg',
                'description' => 'Custom made-to-measure alcove wall shelving with colored dividers for living room display and storage.',
                'status' => 'Active',
            ],
            [
                'title' => 'Razor-Sharp Wall & Ceiling Cutting-In Detail',
                'category' => 'Painting & Decorating',
                'categoryKey' => 'painting',
                'location' => 'Waterloo, Liverpool',
                'tag' => 'Precision Detail',
                'image' => '/images/gallery/sk-home-solutions-precision-wall-painting-detail.png',
                'description' => 'Close-up craftsmanship showing straight, crisp boundary lines between vibrant wall emulsion and crisp ceiling white.',
                'status' => 'Active',
            ],
            [
                'title' => 'Textured Timber-Effect Accent Wallpaper',
                'category' => 'Wallpapering & Murals',
                'categoryKey' => 'wallpaper',
                'location' => 'Liverpool City Centre',
                'tag' => 'Feature Wallpaper',
                'image' => '/images/gallery/sk-home-solutions-peel-and-stick-wood-look-wallpaper.jpeg',
                'description' => 'Modern peel-and-stick wood plank design wallpaper applied to create a rustic Scandinavian feature wall.',
                'status' => 'Active',
            ],
            [
                'title' => 'Precision Mitered Timber Corner Detail',
                'category' => 'Carpentry & Joinery',
                'categoryKey' => 'carpentry',
                'location' => 'Liverpool City Centre',
                'tag' => 'Fine Joinery',
                'image' => '/images/gallery/sk-home-solutions-fine-wood-joinery-corner-detail.jpeg',
                'description' => 'Tight 45-degree mitered joinery corner with zero gaps, smooth sanding, and natural grain matching.',
                'status' => 'Active',
            ],
            [
                'title' => 'Complete Room Transformation With Fresh Paint',
                'category' => 'Painting & Decorating',
                'categoryKey' => 'painting',
                'location' => 'Woolton, Liverpool',
                'tag' => 'Full Refresh',
                'image' => '/images/gallery/sk-home-solutions-room-transformation-with-fresh-paint.jpeg',
                'description' => 'Full overhaul of an older room including wall plaster preparation, undercoating, and two coats of washable matt.',
                'status' => 'Active',
            ],
            [
                'title' => 'Precision Wallpaper Alignment & Edge Trimming',
                'category' => 'Wallpapering & Murals',
                'categoryKey' => 'wallpaper',
                'location' => 'Waterloo, Liverpool',
                'tag' => 'Wallpaper Prep',
                'image' => '/images/gallery/sk-home-solutions-precision-wallpaper-trimming.jpeg',
                'description' => 'Master paperhanger trimming excess top edge with straight-edge guide for razor-sharp ceiling integration.',
                'status' => 'Active',
            ],
            [
                'title' => 'Heavy-Duty Wall TV Bracket Installation Close-Up',
                'category' => 'TV Media Walls & Mounting',
                'categoryKey' => 'media-wall',
                'location' => 'Formby, Merseyside',
                'tag' => 'TV Mounting',
                'image' => '/images/gallery/sk-home-solutions-tv-wall-bracket-installation-close-up.jpg',
                'description' => 'Solid steel TV mounting bracket securely fastened with heavy-duty masonry anchors and spirit level precision.',
                'status' => 'Active',
            ],
            [
                'title' => 'Master Furniture Joint & Framing Craftsmanship',
                'category' => 'Carpentry & Joinery',
                'categoryKey' => 'carpentry',
                'location' => 'Sefton, Merseyside',
                'tag' => 'Cabinet Joinery',
                'image' => '/images/gallery/sk-home-solutions-fine-furniture-joint-craftsmanship.jpeg',
                'description' => 'Handcrafted mortise and tenon wood framing showing seamless timber joints and structural strength.',
                'status' => 'Active',
            ],
            [
                'title' => 'Smooth Roller Interior Wall Decorating',
                'category' => 'Painting & Decorating',
                'categoryKey' => 'painting',
                'location' => 'West Derby, Liverpool',
                'tag' => 'Interior Painting',
                'image' => '/images/gallery/sk-home-solutions-interior-wall-painting-service.jpg',
                'description' => 'Uniform emulsion rolling across expansive residential walls with high-coverage trade paint.',
                'status' => 'Active',
            ],
            [
                'title' => 'Luxury Living Room Full Room Refresh',
                'category' => 'Property Refurbishment',
                'categoryKey' => 'refurbishment',
                'location' => 'Formby, Merseyside',
                'tag' => 'Full Refresh',
                'image' => '/images/gallery/sk-home-solutions-luxury-living-room-interior-design-inspiration.webp',
                'description' => 'Complete interior overhaul featuring new painted walls, woodwork refurbishment, and coordinated luxury decor.',
                'status' => 'Active',
            ],
            [
                'title' => 'Coastal Themed Bedroom Decor & Finish',
                'category' => 'Property Refurbishment',
                'categoryKey' => 'refurbishment',
                'location' => 'Southport, Merseyside',
                'tag' => 'Bedroom Refresh',
                'image' => '/images/gallery/sk-home-solutions-coastal-themed-bedroom-decor-inspiration.jpeg',
                'description' => 'Light, airy coastal themed bedroom transformation with crisp neutral walls, wood accents, and natural lighting.',
                'status' => 'Active',
            ]
        ];

        foreach ($projects as $project) {
            Project::create($project);
        }
    }
}
